Refactor Jenkinsfile to manage Terraform actions
Updated Jenkinsfile to include Terraform commands and actions.

diff --git a/jenkinsfile b/jenkinsfile
--- a/jenkinsfile
+++ b/jenkinsfile
@@ -1,13 +1,24 @@
-provider "aws" {
-  region     = "us-east-1"
-}
+#!/bin/bash
+set -e
 
-resource "aws_instance" "example" {
-  count         = 5
-  ami           = "ami-0bb7267a511c0a8e8"
-  instance_type = "t3.micro"
+echo "Terraform action selected: $TF_ACTION"
+echo "Workspace: $(pwd)"
 
-  tags = {
-    Name = "HelloWorld"
-  }
-}
+terraform --version
+
+echo "Initializing Terraform..."
+terraform init
+
+echo "Running Terraform Plan..."
+terraform plan
+
+if [ "$TF_ACTION" = "apply" ]; then
+    echo "Applying Terraform..."
+    terraform apply -auto-approve
+elif [ "$TF_ACTION" = "destroy" ]; then
+    echo "Destroying Terraform resources..."
+    terraform destroy -auto-approve
+else
+    echo "Invalid Terraform action"
+    exit 1
+fi
